name: Release

on:
  release:
    types: [released]

permissions:
  attestations: write
  contents: write
  id-token: write

jobs:
  upload:
    uses: dtolnay/.github/.github/workflows/release_tgz.yml@master
